name: Build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.github_token }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${REPO}:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${REPO}:${{ github.sha }}
          docker push ghcr.io/${REPO}:latest

      - name: Cleanup
        run: |
          docker builder prune -a -f
          docker logout ghcr.io

